# Generated by Django 4.1.1 on 2022-10-06 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(blank=True, max_length=250)),
                ('cafe_bio', models.CharField(blank=True, max_length=2500)),
                ('date_founded', models.DateField()),
                ('address_line_1', models.CharField(blank=True, max_length=250)),
                ('address_line_2', models.CharField(blank=True, max_length=250)),
                ('address_city', models.CharField(blank=True, max_length=250)),
                ('address_county', models.CharField(blank=True, max_length=250)),
                ('address_country', models.CharField(blank=True, max_length=250)),
                ('address_postcode', models.CharField(blank=True, max_length=10)),
                ('cafe_image', models.ImageField(default='no image uploaded', upload_to='main_app/static/uploads')),
                ('menu_image', models.ImageField(default='no image uploaded', upload_to='main_app/static/uploads')),
                ('cafe_website', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CafeOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_open', models.CharField(max_length=250)),
                ('open_from', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('variety', models.CharField(choices=[('A', 'Arabica'), ('R', 'Robusta'), ('L', 'Liberica'), ('E', 'Excelsa')], default='A', max_length=1000)),
                ('description', models.CharField(max_length=2000)),
                ('roastery', models.CharField(max_length=250)),
                ('date_harvested', models.CharField(max_length=250)),
                ('image', models.ImageField(default='no image uploaded', upload_to='main_app/static/uploads')),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('stars', models.CharField(choices=[('5', '★★★★★'), ('4', '★★★★'), ('3', '★★★'), ('2', '★★'), ('1', '★')], default='5', max_length=2)),
                ('review_title', models.CharField(max_length=250)),
                ('review_body', models.CharField(max_length=1000)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cafe')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cafe_owner', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('event_description', models.CharField(max_length=1000)),
                ('event_type', models.CharField(choices=[('KID', 'Children'), ('MUM', 'Parent and Children'), ('HEA', 'Health and Wellbeing'), ('FIT', 'Fitness'), ('FOO', 'Cooking and Food'), ('ENT', 'Entertainment'), ('ART', 'Arts and Crafts')], default='KID', max_length=4)),
                ('event_date', models.DateField()),
                ('event_time_from', models.TimeField()),
                ('event_time_to', models.TimeField()),
                ('event_image', models.ImageField(default='no image uploaded', upload_to='main_app/static/uploads')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cafe')),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='coffee_beans',
            field=models.ManyToManyField(blank=True, to='main_app.coffeebean'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BrewingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(choices=[('DB', 'Drip Brewed'), ('P', 'Percolator'), ('FP', 'French Press'), ('C', 'Chezve'), ('P', 'Pour-over'), ('S', 'Syphon'), ('CM', 'Coffee Maker'), ('V', 'V60'), ('AP', 'Aeropress')], default='DB', max_length=2)),
                ('method_image', models.ImageField(default='no image uploaded', upload_to='main_app/static/uploads')),
                ('method_bio', models.CharField(max_length=300)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cafe')),
            ],
        ),
    ]
