# Generated by Django 4.1.1 on 2022-10-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cafe_coffee_beans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='coffee_beans',
        ),
        migrations.AddField(
            model_name='brewingmethod',
            name='cafe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.cafe'),
            preserve_default=False,
        ),
    ]
