# Generated by Django 4.1.1 on 2022-10-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_cafe_coffee_beans_brewingmethod_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewingmethod',
            name='brewing_method',
            field=models.CharField(choices=[('A', 'Arabica'), ('R', 'Robusta'), ('L', 'Liberica'), ('E', 'Excelsa')], default='A', max_length=1),
        ),
    ]
