# Generated by Django 4.1.1 on 2022-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_cafe_coffee_beans_brewingmethod_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='coffee_beans',
            field=models.ManyToManyField(to='main_app.coffeebean'),
        ),
    ]
