# Generated by Django 4.1.1 on 2022-10-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_brewingmethod_brewing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewingmethod',
            name='brewing_method_image',
            field=models.ImageField(default='no image uploaded', upload_to='main_app/static/uploads'),
        ),
        migrations.AlterField(
            model_name='brewingmethod',
            name='brewing_method',
            field=models.CharField(choices=[('DB', 'Drip Brewed'), ('P', 'Percolator'), ('FP', 'French Press'), ('C', 'Chezve'), ('P', 'Pour-over'), ('S', 'Syphon'), ('CM', 'Coffee Maker')], default='DB', max_length=2),
        ),
    ]