# Generated by Django 4.1.1 on 2022-10-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cafe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='address_line_2',
            field=models.CharField(default='left blank', max_length=250),
        ),
    ]
