# Generated by Django 4.1.1 on 2022-10-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_brewingmethod_brewing_method_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewingmethod',
            old_name='brewing_method_image',
            new_name='method_image',
        ),
        migrations.RenameField(
            model_name='brewingmethod',
            old_name='brewing_method',
            new_name='method_name',
        ),
        migrations.AddField(
            model_name='brewingmethod',
            name='method_bio',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
