# Generated by Django 4.1.1 on 2022-10-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_coffee_bean_description_coffeebean_description_and_more'),
        ('main_app', '0006_rename_brewing_method_image_brewingmethod_method_image_and_more'),
    ]

    operations = [
    ]
