# Generated by Django 4.1.1 on 2022-10-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_coffee_bean_description_coffeebean_description_and_more'),
        ('main_app', '0006_alter_cafe_address_line_2'),
    ]

    operations = [
    ]
