# Generated by Django 4.1.1 on 2022-10-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_20221004_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='address_city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_country',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_county',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='cafe_bio',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='cafe_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]