# Generated by Django 4.1.1 on 2022-10-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_cafe_address_city_alter_cafe_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='coffee_beans',
            field=models.ManyToManyField(blank=True, to='main_app.coffeebean'),
        ),
    ]
