# Generated by Django 4.1.1 on 2022-10-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_cafe_coffee_beans_remove_event_event_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='no image uploaded', upload_to='main_app/static/uploads'),
        ),
    ]
