# Generated by Django 4.1.1 on 2022-10-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_event_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewingmethod',
            old_name='cafe',
            new_name='method_cafe',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='cafe',
            new_name='event_cafe',
        ),
    ]