# Generated by Django 4.1.1 on 2022-10-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_brewing_method_image_brewingmethod_method_image_and_more'),
        ('main_app', '0009_alter_cafe_coffee_beans'),
    ]

    operations = [
    ]
