# Generated by Django 4.1.1 on 2022-10-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20221004_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewingmethod',
            name='method_name',
            field=models.CharField(choices=[('DB', 'Drip Brewed'), ('P', 'Percolator'), ('FP', 'French Press'), ('C', 'Chezve'), ('P', 'Pour-over'), ('S', 'Syphon'), ('CM', 'Coffee Maker'), ('V', 'V60'), ('AP', 'Aeropress')], default='DB', max_length=2),
        ),
    ]