# Generated by Django 4.1.1 on 2022-10-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_20221004_1920'),
        ('main_app', '0013_alter_profile_profile_type_alter_profile_user'),
    ]

    operations = [
    ]
