# Generated by Django 4.1.1 on 2022-10-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_merge_20221005_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='coffee_beans',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='user',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_city',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_country',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_county',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_line_1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_line_2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_postcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='cafe_bio',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='cafe_name',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
