# Generated by Django 4.1.1 on 2022-10-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_merge_20221004_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('O', 'Cafe Owner'), ('U', 'Bean Fiend')], default='O', max_length=250),
        ),
    ]
