# Generated by Django 4.1.1 on 2022-10-05 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0016_cafe_coffee_beans_cafe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='address_city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_country',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_county',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='cafe_bio',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='cafe_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='coffee_beans',
            field=models.ManyToManyField(blank=True, to='main_app.coffeebean'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('O', 'Cafe Owner'), ('U', 'Bean Fiend')], default='O', max_length=250)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
