# Generated by Django 4.1.1 on 2022-10-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_cafe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_cafe_owner',
            field=models.BooleanField(null=True),
        ),
    ]
