# Generated by Django 4.1.1 on 2022-10-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_cafe_brewingmethod_method_cafe_and_more'),
        ('main_app', '0017_alter_cafe_address_city_alter_cafe_address_country_and_more'),
    ]

    operations = [
    ]
