# Generated by Django 4.1.1 on 2022-10-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_profile_profile_type_profile_is_cafe_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_cafe_owner',
            field=models.BooleanField(default=False),
        ),
    ]
