# Generated by Django 4.1.1 on 2022-10-06 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0018_merge_20221005_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewingmethod',
            old_name='method_cafe',
            new_name='cafe',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_cafe',
            new_name='cafe',
        ),
        migrations.AddField(
            model_name='cafe',
            name='coffee_beans',
            field=models.ManyToManyField(blank=True, to='main_app.coffeebean'),
        ),
        migrations.AddField(
            model_name='review',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.cafe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
