# Generated by Django 4.1.1 on 2022-10-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_rename_method_cafe_brewingmethod_cafe_and_more0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
