# Generated by Django 4.1.1 on 2022-11-21 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0020_alter_review_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_cafe_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
