# Generated by Django 4.1.1 on 2022-10-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_rename_method_cafe_brewingmethod_cafe_and_more'),
        ('main_app', '0020_review_cafe_review_user'),
    ]

    operations = [
    ]
