# Generated by Django 4.1.1 on 2022-11-26 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0021_remove_profile_profile_type_profile_is_cafe_owner_and_more12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
