# Generated by Django 4.1.1 on 2022-11-26 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0022_alter_cafe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_cafe_owner',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
