# Generated by Django 4.1.1 on 2022-11-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_cafe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='latitude',
            field=models.DecimalField(decimal_places=25, max_digits=250, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='longitude',
            field=models.DecimalField(decimal_places=25, max_digits=250, null=True),
        ),
    ]
